
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action ViewAction;

	private global::Gtk.Action AnalysisAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action NewSubjectAction;

	private global::Gtk.Action QuickStartAction;

	private global::Gtk.Action PreferencesAction;

	private global::Gtk.Action LoadPreviousAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action HelpAction1;

	private global::Gtk.Action AboutAction1;

	private global::Gtk.Action DataQualityReportAction;

	private global::Gtk.ToggleAction HyperscanningViewAction;

	private global::Gtk.ToggleAction ShowSystemMessagingAction;

	private global::Gtk.Action RegisterProbeAction;

	private global::Gtk.Action RunGLMAnalysisAction;

	private global::Gtk.VBox vbox5;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HSeparator hseparator5;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox8;

	private global::Gtk.VBox vbox11;

	private global::Gtk.HBox hbox9;

	private global::Gtk.ComboBox combobox_device1;

	private global::Gtk.Fixed fixed_device1;

	private global::Gtk.DrawingArea drawingarea_Data;

	private global::Gtk.HBox hbox10;

	private global::Gtk.ComboBox combobox_device2;

	private global::Gtk.Fixed fixed_device2;

	private global::Gtk.DrawingArea drawingarea_Data2;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment19;

	private global::Gtk.HBox hbox6;

	private global::Gtk.VBox vbox9;

	private global::Gtk.ComboBox combobox_whichdata;

	private global::Gtk.CheckButton checkbutton1;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Label label50;

	private global::Gtk.Entry entry1;

	private global::Gtk.CheckButton checkbutton3;

	private global::Gtk.Label GtkLabel59;

	private global::Gtk.Fixed fixed5;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label2;

	private global::Gtk.ComboBox combobox_selectview;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox10;

	private global::Gtk.DrawingArea drawingarea_SDG;

	private global::Gtk.DrawingArea drawingarea_SDG2;

	private global::Gtk.Label GtkLabel52;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Frame frame21;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button1;

	private global::Gtk.ColorButton colorbutton1;

	private global::Gtk.ProgressBar progressbar1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Button button3;

	private global::Gtk.ToggleButton togglebutton1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.ComboBoxEntry comboboxentry1;

	private global::Gtk.Label label9;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Button button2;

	private global::Gtk.Button button4;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.Label GtkLabel11;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Notebook notebook_detectors;

	private global::Gtk.Label label8;

	private global::Gtk.HBox hbox7;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label7;

	private global::Gtk.SpinButton spinbutton1;

	private global::Gtk.Fixed fixed15;

	private global::Gtk.Label label1;

	private global::Gtk.VBox vbox42;

	private global::Gtk.Notebook notebook_sources;

	private global::Gtk.Label label10;

	private global::Gtk.HBox hbox13;

	private global::Gtk.Fixed fixed11;

	private global::Gtk.Label label49;

	private global::Gtk.SpinButton spinbutton3;

	private global::Gtk.Fixed fixed13;

	private global::Gtk.CheckButton checkbutton_linklasers;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox43;

	private global::Gtk.HBox hbox14;

	private global::Gtk.VBox vbox48;

	private global::Gtk.Frame frame23;

	private global::Gtk.Alignment GtkAlignment22;

	private global::Gtk.VBox vbox49;

	private global::Gtk.HBox hbox31;

	private global::Gtk.Label label52;

	private global::Gtk.Entry entry5;

	private global::Gtk.CheckButton checkbutton10;

	private global::Gtk.HBox hbox32;

	private global::Gtk.Label label53;

	private global::Gtk.Entry entry6;

	private global::Gtk.CheckButton checkbutton11;

	private global::Gtk.HSeparator hseparator4;

	private global::Gtk.CheckButton checkbutton12;

	private global::Gtk.Label GtkLabel70;

	private global::Gtk.Frame frame24;

	private global::Gtk.Alignment GtkAlignment23;

	private global::Gtk.CheckButton checkbutton14;

	private global::Gtk.Label GtkLabel67;

	private global::Gtk.Frame frame25;

	private global::Gtk.Alignment GtkAlignment24;

	private global::Gtk.Label GtkLabel68;

	private global::Gtk.Label label5;

	private global::Gtk.Label label6;

	private global::Gtk.Label GtkLabel69;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.ViewAction = new global::Gtk.Action("ViewAction", global::Mono.Unix.Catalog.GetString("View "), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Register Probe");
		w1.Add(this.ViewAction, null);
		this.AnalysisAction = new global::Gtk.Action("AnalysisAction", global::Mono.Unix.Catalog.GetString("Analysis"), null, null);
		this.AnalysisAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.AnalysisAction, null);
		this.AboutAction = new global::Gtk.Action("AboutAction", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction, null);
		this.NewSubjectAction = new global::Gtk.Action("NewSubjectAction", global::Mono.Unix.Catalog.GetString("New Subject"), null, null);
		this.NewSubjectAction.ShortLabel = global::Mono.Unix.Catalog.GetString("New Subject");
		w1.Add(this.NewSubjectAction, null);
		this.QuickStartAction = new global::Gtk.Action("QuickStartAction", global::Mono.Unix.Catalog.GetString("Quick Start"), null, null);
		this.QuickStartAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Quick Start");
		w1.Add(this.QuickStartAction, null);
		this.PreferencesAction = new global::Gtk.Action("PreferencesAction", global::Mono.Unix.Catalog.GetString("Preferences"), null, null);
		this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Preferences");
		w1.Add(this.PreferencesAction, null);
		this.LoadPreviousAction = new global::Gtk.Action("LoadPreviousAction", global::Mono.Unix.Catalog.GetString("Load Previous"), null, null);
		this.LoadPreviousAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Previous");
		w1.Add(this.LoadPreviousAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.HelpAction1 = new global::Gtk.Action("HelpAction1", global::Mono.Unix.Catalog.GetString("Help"), null, null);
		this.HelpAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Help");
		w1.Add(this.HelpAction1, null);
		this.AboutAction1 = new global::Gtk.Action("AboutAction1", global::Mono.Unix.Catalog.GetString("About"), null, null);
		this.AboutAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("About");
		w1.Add(this.AboutAction1, null);
		this.DataQualityReportAction = new global::Gtk.Action("DataQualityReportAction", global::Mono.Unix.Catalog.GetString("Data Quality Report"), null, null);
		this.DataQualityReportAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Data Quality Report");
		w1.Add(this.DataQualityReportAction, null);
		this.HyperscanningViewAction = new global::Gtk.ToggleAction("HyperscanningViewAction", global::Mono.Unix.Catalog.GetString("Hyperscanning view"), null, null);
		this.HyperscanningViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Hyperscanning view");
		w1.Add(this.HyperscanningViewAction, null);
		this.ShowSystemMessagingAction = new global::Gtk.ToggleAction("ShowSystemMessagingAction", global::Mono.Unix.Catalog.GetString("Show System Messaging"), null, null);
		this.ShowSystemMessagingAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Show System Messaging");
		w1.Add(this.ShowSystemMessagingAction, null);
		this.RegisterProbeAction = new global::Gtk.Action("RegisterProbeAction", global::Mono.Unix.Catalog.GetString("Register Probe"), null, null);
		this.RegisterProbeAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Register Probe");
		w1.Add(this.RegisterProbeAction, null);
		this.RunGLMAnalysisAction = new global::Gtk.Action("RunGLMAnalysisAction", global::Mono.Unix.Catalog.GetString("Run GLM Analysis"), null, null);
		this.RunGLMAnalysisAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Run GLM Analysis");
		w1.Add(this.RunGLMAnalysisAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 2000;
		this.HeightRequest = 800;
		this.CanFocus = true;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("NIRSRecordIR");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.BorderWidth = ((uint)(6));
		this.AllowShrink = true;
		this.DefaultWidth = 1400;
		this.DefaultHeight = 800;
		this.DestroyWithParent = true;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 1;
		// Container child vbox5.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='NewSubjectAction' action='NewSubjectAction'/><menuitem name='QuickStartAction' action='QuickStartAction'/><menuitem name='PreferencesAction' action='PreferencesAction'/><menuitem name='LoadPreviousAction' action='LoadPreviousAction'/><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='DataQualityReportAction' action='DataQualityReportAction'/><menuitem name='HyperscanningViewAction' action='HyperscanningViewAction'/><menuitem name='ShowSystemMessagingAction' action='ShowSystemMessagingAction'/></menu><menu name='AnalysisAction' action='AnalysisAction'><menu name='RegisterProbeAction' action='RegisterProbeAction'/><menuitem name='RunGLMAnalysisAction' action='RunGLMAnalysisAction'/></menu><menu name='AboutAction' action='AboutAction'><menuitem name='HelpAction1' action='HelpAction1'/><menuitem name='AboutAction1' action='AboutAction1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox5.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		w2.Padding = ((uint)(3));
		// Container child vbox5.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator();
		this.hseparator5.Name = "hseparator5";
		this.vbox5.Add(this.hseparator5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hseparator5]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(1));
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.WidthRequest = 800;
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.combobox_device1 = global::Gtk.ComboBox.NewText();
		this.combobox_device1.Name = "combobox_device1";
		this.hbox9.Add(this.combobox_device1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.combobox_device1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed_device1 = new global::Gtk.Fixed();
		this.fixed_device1.Name = "fixed_device1";
		this.fixed_device1.HasWindow = false;
		this.hbox9.Add(this.fixed_device1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed_device1]));
		w5.Position = 1;
		this.vbox11.Add(this.hbox9);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox9]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.drawingarea_Data = new global::Gtk.DrawingArea();
		this.drawingarea_Data.Name = "drawingarea_Data";
		this.vbox11.Add(this.drawingarea_Data);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.drawingarea_Data]));
		w7.Position = 1;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.combobox_device2 = global::Gtk.ComboBox.NewText();
		this.combobox_device2.Name = "combobox_device2";
		this.hbox10.Add(this.combobox_device2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.combobox_device2]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fixed_device2 = new global::Gtk.Fixed();
		this.fixed_device2.Name = "fixed_device2";
		this.fixed_device2.HasWindow = false;
		this.hbox10.Add(this.fixed_device2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.fixed_device2]));
		w9.Position = 1;
		this.vbox11.Add(this.hbox10);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox10]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.drawingarea_Data2 = new global::Gtk.DrawingArea();
		this.drawingarea_Data2.Name = "drawingarea_Data2";
		this.vbox11.Add(this.drawingarea_Data2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.drawingarea_Data2]));
		w11.Position = 3;
		this.vbox8.Add(this.vbox11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox11]));
		w12.Position = 0;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox8.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hseparator2]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment19 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment19.Name = "GtkAlignment19";
		this.GtkAlignment19.LeftPadding = ((uint)(12));
		// Container child GtkAlignment19.Gtk.Container+ContainerChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.combobox_whichdata = global::Gtk.ComboBox.NewText();
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Raw 690nm"));
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Raw 830nm"));
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Optical Density 690nm (filtered)"));
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Optical Density 830nm (filtered)"));
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Oxy-Hemoglobin (filtered)"));
		this.combobox_whichdata.AppendText(global::Mono.Unix.Catalog.GetString("Deoxy-Hemoglobin (filtered)"));
		this.combobox_whichdata.Name = "combobox_whichdata";
		this.combobox_whichdata.Active = 0;
		this.vbox9.Add(this.combobox_whichdata);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.combobox_whichdata]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Auto-scale Y-axis");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.vbox9.Add(this.checkbutton1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.checkbutton1]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label50 = new global::Gtk.Label();
		this.label50.Name = "label50";
		this.label50.LabelProp = global::Mono.Unix.Catalog.GetString("Window X-axis");
		this.hbox8.Add(this.label50);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label50]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString("60");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.hbox8.Add(this.entry1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.entry1]));
		w17.Position = 1;
		// Container child hbox8.Gtk.Box+BoxChild
		this.checkbutton3 = new global::Gtk.CheckButton();
		this.checkbutton3.CanFocus = true;
		this.checkbutton3.Name = "checkbutton3";
		this.checkbutton3.Label = "";
		this.checkbutton3.DrawIndicator = true;
		this.checkbutton3.UseUnderline = true;
		this.hbox8.Add(this.checkbutton3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkbutton3]));
		w18.Position = 2;
		this.vbox9.Add(this.hbox8);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox8]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox6.Add(this.vbox9);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox9]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		this.GtkAlignment19.Add(this.hbox6);
		this.frame4.Add(this.GtkAlignment19);
		this.GtkLabel59 = new global::Gtk.Label();
		this.GtkLabel59.Name = "GtkLabel59";
		this.GtkLabel59.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Display Settings</b>");
		this.GtkLabel59.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel59;
		this.hbox5.Add(this.frame4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.frame4]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox5.Add(this.fixed5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.fixed5]));
		w24.Position = 1;
		this.vbox8.Add(this.hbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox5]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.hbox1.Add(this.vbox8);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox8]));
		w26.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox1.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Draw Mode");
		this.hbox3.Add(this.label2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.combobox_selectview = global::Gtk.ComboBox.NewText();
		this.combobox_selectview.AppendText(global::Mono.Unix.Catalog.GetString("Flat View"));
		this.combobox_selectview.AppendText(global::Mono.Unix.Catalog.GetString("10-20 View"));
		this.combobox_selectview.Name = "combobox_selectview";
		this.combobox_selectview.Active = 0;
		this.hbox3.Add(this.combobox_selectview);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.combobox_selectview]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.drawingarea_SDG = new global::Gtk.DrawingArea();
		this.drawingarea_SDG.HeightRequest = 163;
		this.drawingarea_SDG.Name = "drawingarea_SDG";
		this.vbox10.Add(this.drawingarea_SDG);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.drawingarea_SDG]));
		w31.Position = 0;
		// Container child vbox10.Gtk.Box+BoxChild
		this.drawingarea_SDG2 = new global::Gtk.DrawingArea();
		this.drawingarea_SDG2.HeightRequest = 163;
		this.drawingarea_SDG2.Name = "drawingarea_SDG2";
		this.vbox10.Add(this.drawingarea_SDG2);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.drawingarea_SDG2]));
		w32.Position = 1;
		this.GtkAlignment2.Add(this.vbox10);
		this.frame2.Add(this.GtkAlignment2);
		this.GtkLabel52 = new global::Gtk.Label();
		this.GtkLabel52.Name = "GtkLabel52";
		this.GtkLabel52.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Probe Layout</b>");
		this.GtkLabel52.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel52;
		this.vbox1.Add(this.frame2);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame2]));
		w35.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame21 = new global::Gtk.Frame();
		this.frame21.Name = "frame21";
		this.frame21.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame21.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.WidthRequest = 71;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.hbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button1]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.colorbutton1 = new global::Gtk.ColorButton();
		this.colorbutton1.CanFocus = true;
		this.colorbutton1.Events = ((global::Gdk.EventMask)(784));
		this.colorbutton1.Name = "colorbutton1";
		this.hbox2.Add(this.colorbutton1);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.colorbutton1]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar();
		this.progressbar1.Name = "progressbar1";
		this.hbox2.Add(this.progressbar1);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.progressbar1]));
		w39.Position = 2;
		this.vbox3.Add(this.hbox2);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox2]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Mark Event");
		this.vbox2.Add(this.button3);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button3]));
		w41.Position = 0;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.togglebutton1 = new global::Gtk.ToggleButton();
		this.togglebutton1.CanFocus = true;
		this.togglebutton1.Name = "togglebutton1";
		this.togglebutton1.UseUnderline = true;
		this.togglebutton1.Active = true;
		this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString("Toggle On");
		this.vbox2.Add(this.togglebutton1);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.togglebutton1]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		this.hbox4.Add(this.vbox2);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox2]));
		w43.Position = 0;
		w43.Expand = false;
		w43.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
		this.comboboxentry1.Name = "comboboxentry1";
		this.vbox4.Add(this.comboboxentry1);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.comboboxentry1]));
		w44.Position = 0;
		w44.Expand = false;
		w44.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("#events = 0");
		this.vbox4.Add(this.label9);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label9]));
		w45.Position = 1;
		w45.Expand = false;
		w45.Fill = false;
		this.hbox4.Add(this.vbox4);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
		w46.Position = 1;
		w46.Expand = false;
		w46.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox4.Add(this.fixed2);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fixed2]));
		w47.PackType = ((global::Gtk.PackType)(1));
		w47.Position = 2;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Auto-Adjust");
		this.vbox7.Add(this.button2);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button2]));
		w48.Position = 0;
		w48.Expand = false;
		w48.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Sources On");
		this.vbox7.Add(this.button4);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button4]));
		w49.Position = 1;
		w49.Expand = false;
		w49.Fill = false;
		this.hbox4.Add(this.vbox7);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
		w50.PackType = ((global::Gtk.PackType)(1));
		w50.Position = 3;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.hbox4.Add(this.fixed3);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fixed3]));
		w51.PackType = ((global::Gtk.PackType)(1));
		w51.Position = 4;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox3.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator3]));
		w53.Position = 2;
		w53.Expand = false;
		w53.Fill = false;
		this.GtkAlignment.Add(this.vbox3);
		this.frame21.Add(this.GtkAlignment);
		this.GtkLabel11 = new global::Gtk.Label();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Aquistion</b>");
		this.GtkLabel11.UseMarkup = true;
		this.frame21.LabelWidget = this.GtkLabel11;
		this.vbox1.Add(this.frame21);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame21]));
		w56.Position = 3;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(4));
		this.frame7.BorderWidth = ((uint)(8));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.WidthRequest = 524;
		this.notebook1.HeightRequest = 200;
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
		this.notebook1.BorderWidth = ((uint)(6));
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.notebook_detectors = new global::Gtk.Notebook();
		this.notebook_detectors.CanFocus = true;
		this.notebook_detectors.Name = "notebook_detectors";
		this.notebook_detectors.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w57 = new global::Gtk.Label();
		w57.Visible = true;
		this.notebook_detectors.Add(w57);
		this.label8 = new global::Gtk.Label();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.notebook_detectors.SetTabLabel(w57, this.label8);
		this.label8.ShowAll();
		this.vbox6.Add(this.notebook_detectors);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.notebook_detectors]));
		w58.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox7.Add(this.fixed1);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.fixed1]));
		w59.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Set All");
		this.hbox7.Add(this.label7);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label7]));
		w60.Position = 1;
		w60.Expand = false;
		w60.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.spinbutton1 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10D;
		this.spinbutton1.ClimbRate = 1D;
		this.spinbutton1.Numeric = true;
		this.spinbutton1.Value = 100D;
		this.hbox7.Add(this.spinbutton1);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.spinbutton1]));
		w61.Position = 2;
		w61.Expand = false;
		w61.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.fixed15 = new global::Gtk.Fixed();
		this.fixed15.Name = "fixed15";
		this.fixed15.HasWindow = false;
		this.hbox7.Add(this.fixed15);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.fixed15]));
		w62.Position = 3;
		this.vbox6.Add(this.hbox7);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
		w63.Position = 1;
		w63.Expand = false;
		w63.Fill = false;
		this.notebook1.Add(this.vbox6);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Detectors");
		this.notebook1.SetTabLabel(this.vbox6, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox42 = new global::Gtk.VBox();
		this.vbox42.Name = "vbox42";
		this.vbox42.Spacing = 6;
		// Container child vbox42.Gtk.Box+BoxChild
		this.notebook_sources = new global::Gtk.Notebook();
		this.notebook_sources.CanFocus = true;
		this.notebook_sources.Name = "notebook_sources";
		this.notebook_sources.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w65 = new global::Gtk.Label();
		w65.Visible = true;
		this.notebook_sources.Add(w65);
		this.label10 = new global::Gtk.Label();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("page1");
		this.notebook_sources.SetTabLabel(w65, this.label10);
		this.label10.ShowAll();
		this.vbox42.Add(this.notebook_sources);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.notebook_sources]));
		w66.Position = 0;
		// Container child vbox42.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.fixed11 = new global::Gtk.Fixed();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.hbox13.Add(this.fixed11);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.fixed11]));
		w67.Position = 0;
		// Container child hbox13.Gtk.Box+BoxChild
		this.label49 = new global::Gtk.Label();
		this.label49.Name = "label49";
		this.label49.LabelProp = global::Mono.Unix.Catalog.GetString("Set All");
		this.hbox13.Add(this.label49);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label49]));
		w68.Position = 1;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.spinbutton3 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbutton3.WidthRequest = 113;
		this.spinbutton3.CanFocus = true;
		this.spinbutton3.Name = "spinbutton3";
		this.spinbutton3.Adjustment.PageIncrement = 10D;
		this.spinbutton3.ClimbRate = 1D;
		this.spinbutton3.Numeric = true;
		this.hbox13.Add(this.spinbutton3);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.spinbutton3]));
		w69.Position = 2;
		w69.Expand = false;
		w69.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.fixed13 = new global::Gtk.Fixed();
		this.fixed13.Name = "fixed13";
		this.fixed13.HasWindow = false;
		this.hbox13.Add(this.fixed13);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.fixed13]));
		w70.Position = 3;
		// Container child hbox13.Gtk.Box+BoxChild
		this.checkbutton_linklasers = new global::Gtk.CheckButton();
		this.checkbutton_linklasers.CanFocus = true;
		this.checkbutton_linklasers.Name = "checkbutton_linklasers";
		this.checkbutton_linklasers.Label = global::Mono.Unix.Catalog.GetString("Link wavelengths");
		this.checkbutton_linklasers.Active = true;
		this.checkbutton_linklasers.DrawIndicator = true;
		this.checkbutton_linklasers.UseUnderline = true;
		this.hbox13.Add(this.checkbutton_linklasers);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.checkbutton_linklasers]));
		w71.Position = 4;
		this.vbox42.Add(this.hbox13);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.hbox13]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		this.notebook1.Add(this.vbox42);
		global::Gtk.Notebook.NotebookChild w73 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox42]));
		w73.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Sources");
		this.notebook1.SetTabLabel(this.vbox42, this.label3);
		this.label3.ShowAll();
		// Notebook tab
		global::Gtk.Label w74 = new global::Gtk.Label();
		w74.Visible = true;
		this.notebook1.Add(w74);
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Events");
		this.notebook1.SetTabLabel(w74, this.label4);
		this.label4.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox43 = new global::Gtk.VBox();
		this.vbox43.Name = "vbox43";
		this.vbox43.Spacing = 6;
		// Container child vbox43.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.vbox48 = new global::Gtk.VBox();
		this.vbox48.Name = "vbox48";
		this.vbox48.Spacing = 6;
		// Container child vbox48.Gtk.Box+BoxChild
		this.frame23 = new global::Gtk.Frame();
		this.frame23.Name = "frame23";
		this.frame23.BorderWidth = ((uint)(6));
		// Container child frame23.Gtk.Container+ContainerChild
		this.GtkAlignment22 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment22.Name = "GtkAlignment22";
		this.GtkAlignment22.LeftPadding = ((uint)(12));
		// Container child GtkAlignment22.Gtk.Container+ContainerChild
		this.vbox49 = new global::Gtk.VBox();
		this.vbox49.Name = "vbox49";
		this.vbox49.Spacing = 6;
		// Container child vbox49.Gtk.Box+BoxChild
		this.hbox31 = new global::Gtk.HBox();
		this.hbox31.Name = "hbox31";
		this.hbox31.Spacing = 6;
		// Container child hbox31.Gtk.Box+BoxChild
		this.label52 = new global::Gtk.Label();
		this.label52.Name = "label52";
		this.label52.LabelProp = global::Mono.Unix.Catalog.GetString("HPF");
		this.hbox31.Add(this.label52);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.label52]));
		w75.Position = 0;
		w75.Expand = false;
		w75.Fill = false;
		// Container child hbox31.Gtk.Box+BoxChild
		this.entry5 = new global::Gtk.Entry();
		this.entry5.CanFocus = true;
		this.entry5.Name = "entry5";
		this.entry5.Text = global::Mono.Unix.Catalog.GetString("0.016");
		this.entry5.IsEditable = true;
		this.entry5.InvisibleChar = '●';
		this.hbox31.Add(this.entry5);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.entry5]));
		w76.Position = 1;
		// Container child hbox31.Gtk.Box+BoxChild
		this.checkbutton10 = new global::Gtk.CheckButton();
		this.checkbutton10.CanFocus = true;
		this.checkbutton10.Name = "checkbutton10";
		this.checkbutton10.Label = "";
		this.checkbutton10.DrawIndicator = true;
		this.checkbutton10.UseUnderline = true;
		this.hbox31.Add(this.checkbutton10);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.checkbutton10]));
		w77.Position = 2;
		this.vbox49.Add(this.hbox31);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.hbox31]));
		w78.Position = 0;
		w78.Expand = false;
		w78.Fill = false;
		// Container child vbox49.Gtk.Box+BoxChild
		this.hbox32 = new global::Gtk.HBox();
		this.hbox32.Name = "hbox32";
		this.hbox32.Spacing = 6;
		// Container child hbox32.Gtk.Box+BoxChild
		this.label53 = new global::Gtk.Label();
		this.label53.Name = "label53";
		this.label53.LabelProp = global::Mono.Unix.Catalog.GetString("LPF");
		this.hbox32.Add(this.label53);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.label53]));
		w79.Position = 0;
		w79.Expand = false;
		w79.Fill = false;
		// Container child hbox32.Gtk.Box+BoxChild
		this.entry6 = new global::Gtk.Entry();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.Text = global::Mono.Unix.Catalog.GetString("0.5");
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.hbox32.Add(this.entry6);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.entry6]));
		w80.Position = 1;
		// Container child hbox32.Gtk.Box+BoxChild
		this.checkbutton11 = new global::Gtk.CheckButton();
		this.checkbutton11.CanFocus = true;
		this.checkbutton11.Name = "checkbutton11";
		this.checkbutton11.Label = "";
		this.checkbutton11.DrawIndicator = true;
		this.checkbutton11.UseUnderline = true;
		this.hbox32.Add(this.checkbutton11);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox32[this.checkbutton11]));
		w81.Position = 2;
		this.vbox49.Add(this.hbox32);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.hbox32]));
		w82.Position = 1;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vbox49.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator();
		this.hseparator4.Name = "hseparator4";
		this.vbox49.Add(this.hseparator4);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.hseparator4]));
		w83.Position = 2;
		w83.Expand = false;
		w83.Fill = false;
		// Container child vbox49.Gtk.Box+BoxChild
		this.checkbutton12 = new global::Gtk.CheckButton();
		this.checkbutton12.CanFocus = true;
		this.checkbutton12.Name = "checkbutton12";
		this.checkbutton12.Label = global::Mono.Unix.Catalog.GetString("Motion Correction");
		this.checkbutton12.DrawIndicator = true;
		this.checkbutton12.UseUnderline = true;
		this.vbox49.Add(this.checkbutton12);
		global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.checkbutton12]));
		w84.Position = 3;
		w84.Expand = false;
		w84.Fill = false;
		this.GtkAlignment22.Add(this.vbox49);
		this.frame23.Add(this.GtkAlignment22);
		this.GtkLabel70 = new global::Gtk.Label();
		this.GtkLabel70.Name = "GtkLabel70";
		this.GtkLabel70.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Filtering</b>");
		this.GtkLabel70.UseMarkup = true;
		this.frame23.LabelWidget = this.GtkLabel70;
		this.vbox48.Add(this.frame23);
		global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.frame23]));
		w87.Position = 0;
		w87.Expand = false;
		w87.Fill = false;
		// Container child vbox48.Gtk.Box+BoxChild
		this.frame24 = new global::Gtk.Frame();
		this.frame24.Name = "frame24";
		this.frame24.BorderWidth = ((uint)(6));
		// Container child frame24.Gtk.Container+ContainerChild
		this.GtkAlignment23 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment23.Name = "GtkAlignment23";
		this.GtkAlignment23.LeftPadding = ((uint)(12));
		// Container child GtkAlignment23.Gtk.Container+ContainerChild
		this.checkbutton14 = new global::Gtk.CheckButton();
		this.checkbutton14.CanFocus = true;
		this.checkbutton14.Name = "checkbutton14";
		this.checkbutton14.Label = global::Mono.Unix.Catalog.GetString("Apply GLM");
		this.checkbutton14.Active = true;
		this.checkbutton14.DrawIndicator = true;
		this.checkbutton14.UseUnderline = true;
		this.GtkAlignment23.Add(this.checkbutton14);
		this.frame24.Add(this.GtkAlignment23);
		this.GtkLabel67 = new global::Gtk.Label();
		this.GtkLabel67.Name = "GtkLabel67";
		this.GtkLabel67.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GLM Statistics</b>");
		this.GtkLabel67.UseMarkup = true;
		this.frame24.LabelWidget = this.GtkLabel67;
		this.vbox48.Add(this.frame24);
		global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.frame24]));
		w90.Position = 1;
		w90.Expand = false;
		w90.Fill = false;
		this.hbox14.Add(this.vbox48);
		global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.vbox48]));
		w91.Position = 0;
		w91.Expand = false;
		w91.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.frame25 = new global::Gtk.Frame();
		this.frame25.Name = "frame25";
		this.frame25.BorderWidth = ((uint)(6));
		// Container child frame25.Gtk.Container+ContainerChild
		this.GtkAlignment24 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment24.Name = "GtkAlignment24";
		this.GtkAlignment24.LeftPadding = ((uint)(12));
		this.frame25.Add(this.GtkAlignment24);
		this.GtkLabel68 = new global::Gtk.Label();
		this.GtkLabel68.Name = "GtkLabel68";
		this.GtkLabel68.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Lab Streaming Layer</b>");
		this.GtkLabel68.UseMarkup = true;
		this.frame25.LabelWidget = this.GtkLabel68;
		this.hbox14.Add(this.frame25);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.frame25]));
		w93.Position = 1;
		w93.Expand = false;
		w93.Fill = false;
		this.vbox43.Add(this.hbox14);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox43[this.hbox14]));
		w94.Position = 0;
		w94.Expand = false;
		w94.Fill = false;
		this.notebook1.Add(this.vbox43);
		global::Gtk.Notebook.NotebookChild w95 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox43]));
		w95.Position = 3;
		// Notebook tab
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Real-time");
		this.notebook1.SetTabLabel(this.vbox43, this.label5);
		this.label5.ShowAll();
		// Notebook tab
		global::Gtk.Label w96 = new global::Gtk.Label();
		w96.Visible = true;
		this.notebook1.Add(w96);
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Data");
		this.notebook1.SetTabLabel(w96, this.label6);
		this.label6.ShowAll();
		this.GtkAlignment4.Add(this.notebook1);
		this.frame7.Add(this.GtkAlignment4);
		this.GtkLabel69 = new global::Gtk.Label();
		this.GtkLabel69.Name = "GtkLabel69";
		this.GtkLabel69.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Instrument Controls </b>");
		this.GtkLabel69.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel69;
		this.vbox1.Add(this.frame7);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.frame7]));
		w99.Position = 4;
		this.hbox1.Add(this.vbox1);
		global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox1]));
		w100.Position = 2;
		w100.Expand = false;
		w100.Fill = false;
		this.vbox5.Add(this.hbox1);
		global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
		w101.Position = 2;
		// Container child vbox5.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox5.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.statusbar1]));
		w102.Position = 3;
		w102.Expand = false;
		w102.Fill = false;
		this.Add(this.vbox5);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.NewSubjectAction.Activated += new global::System.EventHandler(this.RegisterSubject);
		this.PreferencesAction.Activated += new global::System.EventHandler(this.ClickedMenuPrefrences);
		this.ExitAction.Activated += new global::System.EventHandler(this.ExitGUI);
		this.HelpAction1.Activated += new global::System.EventHandler(this.HelpDLG);
		this.AboutAction1.Activated += new global::System.EventHandler(this.AboutDLG);
		this.HyperscanningViewAction.Toggled += new global::System.EventHandler(this.SetHyperscanningView);
		this.ShowSystemMessagingAction.Toggled += new global::System.EventHandler(this.SetShowSystemMsg);
		this.combobox_selectview.Changed += new global::System.EventHandler(this.changeprobe_view);
		this.button4.Clicked += new global::System.EventHandler(this.LasersAllOnOff);
		this.spinbutton1.ValueChanged += new global::System.EventHandler(this.DetGain_SetAll);
		this.spinbutton3.ValueChanged += new global::System.EventHandler(this.SourcePower_SetAll);
	}
}
