
// This file has been generated by the GUI designer. Do not modify.
namespace NIRSrecorder
{
	public partial class PrefrencesWindow
	{
		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Frame frame11;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox11;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label12;

		private global::Gtk.ComboBox combobox8;

		private global::Gtk.Button buttonConnect;

		private global::Gtk.Frame frame13;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textview3;

		private global::Gtk.Label GtkLabel5;

		private global::Gtk.Label GtkLabel3;

		private global::Gtk.Frame frame14;

		private global::Gtk.Alignment GtkAlignment4;

		private global::Gtk.VBox vbox12;

		private global::Gtk.HBox hbox12;

		private global::Gtk.CheckButton checkbutton5;

		private global::Gtk.CheckButton checkbutton7;

		private global::Gtk.Fixed fixed7;

		private global::Gtk.Fixed fixed9;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.Frame frame_debug;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button button_pref_testCOM;

		private global::Gtk.ComboBox combobox_selectSerial;

		private global::Gtk.ComboBoxEntry comboboxentry_debug;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textview_Debug;

		private global::Gtk.Label GtkLabel7;

		private global::Gtk.Label GtkLabel8;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NIRSrecorder.PrefrencesWindow
			this.Name = "NIRSrecorder.PrefrencesWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Preferences");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DestroyWithParent = true;
			// Container child NIRSrecorder.PrefrencesWindow.Gtk.Container+ContainerChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame11 = new global::Gtk.Frame();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame11.BorderWidth = ((uint)(13));
			// Container child frame11.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Port Name");
			this.hbox10.Add(this.label12);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label12]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.combobox8 = global::Gtk.ComboBox.NewText();
			this.combobox8.AppendText(global::Mono.Unix.Catalog.GetString("/dev/usb.tty.serialPort.USB"));
			this.combobox8.Name = "combobox8";
			this.combobox8.Active = 0;
			this.hbox10.Add(this.combobox8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.combobox8]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.buttonConnect = new global::Gtk.Button();
			this.buttonConnect.CanFocus = true;
			this.buttonConnect.Name = "buttonConnect";
			this.buttonConnect.UseUnderline = true;
			this.buttonConnect.Label = global::Mono.Unix.Catalog.GetString("Connect");
			this.hbox10.Add(this.buttonConnect);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.buttonConnect]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox11.Add(this.hbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox10]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.frame13 = new global::Gtk.Frame();
			this.frame13.Name = "frame13";
			this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame13.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textview3 = new global::Gtk.TextView();
			this.textview3.CanFocus = true;
			this.textview3.Name = "textview3";
			this.GtkScrolledWindow1.Add(this.textview3);
			this.GtkAlignment3.Add(this.GtkScrolledWindow1);
			this.frame13.Add(this.GtkAlignment3);
			this.GtkLabel5 = new global::Gtk.Label();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("Connected Devices");
			this.GtkLabel5.UseMarkup = true;
			this.frame13.LabelWidget = this.GtkLabel5;
			this.vbox11.Add(this.frame13);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.frame13]));
			w8.Position = 1;
			this.GtkAlignment2.Add(this.vbox11);
			this.frame11.Add(this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString("<b>COM Connection</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame11.LabelWidget = this.GtkLabel3;
			this.vbox9.Add(this.frame11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame11]));
			w11.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame14 = new global::Gtk.Frame();
			this.frame14.Name = "frame14";
			this.frame14.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame14.BorderWidth = ((uint)(13));
			// Container child frame14.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.checkbutton5 = new global::Gtk.CheckButton();
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString("Save *.nirs format");
			this.checkbutton5.Active = true;
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.hbox12.Add(this.checkbutton5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.checkbutton5]));
			w12.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.checkbutton7 = new global::Gtk.CheckButton();
			this.checkbutton7.CanFocus = true;
			this.checkbutton7.Name = "checkbutton7";
			this.checkbutton7.Label = global::Mono.Unix.Catalog.GetString("Save *.snirf format");
			this.checkbutton7.Active = true;
			this.checkbutton7.DrawIndicator = true;
			this.checkbutton7.UseUnderline = true;
			this.hbox12.Add(this.checkbutton7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.checkbutton7]));
			w13.Position = 1;
			this.vbox12.Add(this.hbox12);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox12]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.vbox12.Add(this.fixed7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.fixed7]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.vbox12.Add(this.fixed9);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.fixed9]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.GtkAlignment4.Add(this.vbox12);
			this.frame14.Add(this.GtkAlignment4);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Options</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame14.LabelWidget = this.GtkLabel6;
			this.vbox9.Add(this.frame14);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame14]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame_debug = new global::Gtk.Frame();
			this.frame_debug.Name = "frame_debug";
			this.frame_debug.ShadowType = ((global::Gtk.ShadowType)(0));
			this.frame_debug.BorderWidth = ((uint)(13));
			// Container child frame_debug.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.button_pref_testCOM = new global::Gtk.Button();
			this.button_pref_testCOM.CanFocus = true;
			this.button_pref_testCOM.Name = "button_pref_testCOM";
			this.button_pref_testCOM.UseUnderline = true;
			this.button_pref_testCOM.Label = global::Mono.Unix.Catalog.GetString("Test COM");
			this.hbox8.Add(this.button_pref_testCOM);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.button_pref_testCOM]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.combobox_selectSerial = global::Gtk.ComboBox.NewText();
			this.combobox_selectSerial.AppendText(global::Mono.Unix.Catalog.GetString("/dev/usb.ttt.serial"));
			this.combobox_selectSerial.Name = "combobox_selectSerial";
			this.combobox_selectSerial.Active = 0;
			this.hbox8.Add(this.combobox_selectSerial);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.combobox_selectSerial]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.comboboxentry_debug = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Lasers All On"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Lasers All Off"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 1 Off"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 1 On"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 2 Off"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 2 On"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 3 Off"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 4 On"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 4 Off"));
			this.comboboxentry_debug.AppendText(global::Mono.Unix.Catalog.GetString("Laser 4 On"));
			this.comboboxentry_debug.AppendText("");
			this.comboboxentry_debug.Name = "comboboxentry_debug";
			this.comboboxentry_debug.Active = 0;
			this.hbox8.Add(this.comboboxentry_debug);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.comboboxentry_debug]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox10.Add(this.hbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox8]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview_Debug = new global::Gtk.TextView();
			this.textview_Debug.CanFocus = true;
			this.textview_Debug.Name = "textview_Debug";
			this.GtkScrolledWindow.Add(this.textview_Debug);
			this.vbox10.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.GtkScrolledWindow]));
			w25.Position = 1;
			this.GtkAlignment1.Add(this.vbox10);
			this.frame_debug.Add(this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Debugging</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame_debug.LabelWidget = this.GtkLabel7;
			this.vbox9.Add(this.frame_debug);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame_debug]));
			w28.Position = 2;
			this.GtkAlignment.Add(this.vbox9);
			this.frame8.Add(this.GtkAlignment);
			this.GtkLabel8 = new global::Gtk.Label();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Prefrences</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel8;
			this.Add(this.frame8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 473;
			this.DefaultHeight = 562;
			this.Show();
			this.button_pref_testCOM.Clicked += new global::System.EventHandler(this.ClickedTestCOM);
			this.comboboxentry_debug.Changed += new global::System.EventHandler(this.EditComboChanged);
		}
	}
}
