
// This file has been generated by the GUI designer. Do not modify.
namespace NIRSrecorder
{
	public partial class Splash
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NIRSrecorder.Splash
			this.Name = "NIRSrecorder.Splash";
			this.Title = global::Mono.Unix.Catalog.GetString("Splash");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
