
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action saveAction;

	private global::Gtk.Action SessionsAction;

	private global::Gtk.Action PreferencesAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.ToggleAction zoomInAction;

	private global::Gtk.ToggleAction zoomOutAction;

	private global::Gtk.Action refreshAction;

	private global::Gtk.ToggleAction ToggleDisplayCountButton;

	private global::Gtk.Action NewRealTimeSessionAction;

	private global::Gtk.Action SaveRealTimeSessionTemplateAction;

	private global::Gtk.Action LoadRealTimeSessionTemplateAction;

	private global::Gtk.Action NewPostSessionAction;

	private global::Gtk.Action SavePostSessionAction;

	private global::Gtk.Action LoadPostSessionAction;

	private global::Gtk.Action LoadDataFileAction;

	private global::Gtk.Action Action;

	private global::Gtk.Action preferencesAction;

	private global::Gtk.Action preferencesAction1;

	private global::Gtk.Action yesAction;

	private global::Gtk.Action addAction;

	private global::Gtk.Action executeAction;

	private global::Gtk.ToggleAction ToggleRTMode;

	private global::Gtk.Action findAction;

	private global::Gtk.Action Action1;

	private global::Gtk.Action SingleDisplay;

	private global::Gtk.Action DualDisplay;

	private global::Gtk.Action aboutAction;

	private global::Gtk.Action addAction1;

	private global::Gtk.Action saveAction1;

	private global::Gtk.Action executeAction1;

	private global::Gtk.Action convertAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.Toolbar toolbar3;

	private global::Gtk.Label GtkLabel2;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment5;

	private global::Gtk.Toolbar toolbar4;

	private global::Gtk.Label GtkLabel10;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.Label GtkLabel3;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment9;

	private global::Gtk.Toolbar toolbar5;

	private global::Gtk.Label GtkLabel12;

	private global::Gtk.Fixed fixed15;

	private global::Gtk.HBox hbox3;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.Frame DatFrame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox2;

	private global::Gtk.DrawingArea drawingareaMain;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Expander expander1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Fixed fixed5;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label1;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label3;

	private global::Gtk.ComboBox combobox3;

	private global::Gtk.Frame frame11;

	private global::Gtk.Alignment GtkAlignment7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview8;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.Label GtkLabel8;

	private global::Gtk.Label GtkLabelData1;

	private global::Gtk.Frame DataFrame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.DrawingArea drawingareaMain1;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.Expander expander2;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Fixed fixed6;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label2;

	private global::Gtk.ComboBox combobox2;

	private global::Gtk.Fixed fixed2;

	private global::Gtk.Label label4;

	private global::Gtk.ComboBox combobox4;

	private global::Gtk.Frame frame13;

	private global::Gtk.Alignment GtkAlignment8;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview7;

	private global::Gtk.Label GtkLabel7;

	private global::Gtk.Label GtkLabel9;

	private global::Gtk.Label GtkLabelData2;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.DrawingArea drawingareaSDG;

	private global::Gtk.Label GtkLabel11;

	private global::Gtk.Fixed fixed3;

	private global::Gtk.Frame frame10;

	private global::Gtk.Alignment GtkAlignment6;

	private global::Gtk.VBox vbox7;

	private global::Gtk.Toolbar toolbar2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeviewData;

	private global::Gtk.Label GtkLabel5;

	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", "File", null, null);
		this.FileAction.ShortLabel = "File";
		w1.Add(this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", "File", null, null);
		this.FileAction1.ShortLabel = "File";
		w1.Add(this.FileAction1, null);
		this.saveAction = new global::Gtk.Action("saveAction", null, null, "gtk-save");
		w1.Add(this.saveAction, null);
		this.SessionsAction = new global::Gtk.Action("SessionsAction", "Sessions", null, null);
		this.SessionsAction.ShortLabel = "Sessions";
		w1.Add(this.SessionsAction, null);
		this.PreferencesAction = new global::Gtk.Action("PreferencesAction", "Preferences", null, null);
		this.PreferencesAction.ShortLabel = "Preferences";
		w1.Add(this.PreferencesAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", "Exit", null, null);
		this.ExitAction.ShortLabel = "Exit";
		w1.Add(this.ExitAction, null);
		this.zoomInAction = new global::Gtk.ToggleAction("zoomInAction", "Zoom In", null, "gtk-zoom-in");
		this.zoomInAction.ShortLabel = "Zoom In";
		w1.Add(this.zoomInAction, null);
		this.zoomOutAction = new global::Gtk.ToggleAction("zoomOutAction", "Zoom Out", null, "gtk-zoom-out");
		this.zoomOutAction.ShortLabel = "Zoom Out";
		w1.Add(this.zoomOutAction, null);
		this.refreshAction = new global::Gtk.Action("refreshAction", "Reset Zoom", null, "gtk-refresh");
		this.refreshAction.ShortLabel = "Reset Zoom";
		w1.Add(this.refreshAction, null);
		this.ToggleDisplayCountButton = new global::Gtk.ToggleAction("ToggleDisplayCountButton", "Dual Display", null, "gtk-dnd-multiple");
		this.ToggleDisplayCountButton.ShortLabel = "Dual Display";
		w1.Add(this.ToggleDisplayCountButton, null);
		this.NewRealTimeSessionAction = new global::Gtk.Action("NewRealTimeSessionAction", "New Real-time Session", null, null);
		this.NewRealTimeSessionAction.ShortLabel = "New Real-time Session";
		w1.Add(this.NewRealTimeSessionAction, null);
		this.SaveRealTimeSessionTemplateAction = new global::Gtk.Action("SaveRealTimeSessionTemplateAction", "Save Real-time Session Template", null, null);
		this.SaveRealTimeSessionTemplateAction.ShortLabel = "Save Real-time Session Template";
		w1.Add(this.SaveRealTimeSessionTemplateAction, null);
		this.LoadRealTimeSessionTemplateAction = new global::Gtk.Action("LoadRealTimeSessionTemplateAction", "Load Real-time Session Template", null, null);
		this.LoadRealTimeSessionTemplateAction.ShortLabel = "Load Real-time Session Template";
		w1.Add(this.LoadRealTimeSessionTemplateAction, null);
		this.NewPostSessionAction = new global::Gtk.Action("NewPostSessionAction", "New Post Session", null, null);
		this.NewPostSessionAction.ShortLabel = "New Post Session";
		w1.Add(this.NewPostSessionAction, null);
		this.SavePostSessionAction = new global::Gtk.Action("SavePostSessionAction", "Save Post Session", null, null);
		this.SavePostSessionAction.ShortLabel = "Save Post Session";
		w1.Add(this.SavePostSessionAction, null);
		this.LoadPostSessionAction = new global::Gtk.Action("LoadPostSessionAction", "Load Post Session", null, null);
		this.LoadPostSessionAction.ShortLabel = "Load Post Session";
		w1.Add(this.LoadPostSessionAction, null);
		this.LoadDataFileAction = new global::Gtk.Action("LoadDataFileAction", "Load data file", null, null);
		this.LoadDataFileAction.ShortLabel = "Load data file";
		w1.Add(this.LoadDataFileAction, null);
		this.Action = new global::Gtk.Action("Action", null, null, null);
		w1.Add(this.Action, null);
		this.preferencesAction = new global::Gtk.Action("preferencesAction", null, null, "gtk-preferences");
		w1.Add(this.preferencesAction, null);
		this.preferencesAction1 = new global::Gtk.Action("preferencesAction1", "Setup", null, "gtk-preferences");
		this.preferencesAction1.ShortLabel = "Setup";
		w1.Add(this.preferencesAction1, null);
		this.yesAction = new global::Gtk.Action("yesAction", "Run", null, "gtk-yes");
		this.yesAction.ShortLabel = "Run";
		w1.Add(this.yesAction, null);
		this.addAction = new global::Gtk.Action("addAction", "Load Data", null, "gtk-add");
		this.addAction.ShortLabel = "Load Data";
		w1.Add(this.addAction, null);
		this.executeAction = new global::Gtk.Action("executeAction", "Edit Demographics", null, "gtk-execute");
		this.executeAction.ShortLabel = "Edit Demographics";
		w1.Add(this.executeAction, null);
		this.ToggleRTMode = new global::Gtk.ToggleAction("ToggleRTMode", "Post-analysis", null, "gtk-execute");
		this.ToggleRTMode.ShortLabel = "Post-analysis";
		w1.Add(this.ToggleRTMode, null);
		this.findAction = new global::Gtk.Action("findAction", "Data Cursor", null, "gtk-find");
		this.findAction.ShortLabel = "Data Cursor";
		w1.Add(this.findAction, null);
		this.Action1 = new global::Gtk.Action("Action1", "Save Data", null, "gtk-save");
		this.Action1.ShortLabel = "Save Data";
		w1.Add(this.Action1, null);
		this.SingleDisplay = new global::Gtk.Action("SingleDisplay", "Single View", null, "gtk-dnd");
		this.SingleDisplay.ShortLabel = "Single View";
		w1.Add(this.SingleDisplay, null);
		this.DualDisplay = new global::Gtk.Action("DualDisplay", "Dual Display", null, "gtk-dnd-multiple");
		this.DualDisplay.ShortLabel = "Dual Display";
		w1.Add(this.DualDisplay, null);
		this.aboutAction = new global::Gtk.Action("aboutAction", "Auto-scale", null, "gtk-about");
		this.aboutAction.ShortLabel = "Auto-scale";
		w1.Add(this.aboutAction, null);
		this.addAction1 = new global::Gtk.Action("addAction1", "Add Data ", null, "gtk-add");
		this.addAction1.ShortLabel = "Add Data ";
		w1.Add(this.addAction1, null);
		this.saveAction1 = new global::Gtk.Action("saveAction1", "Save Data", null, "gtk-save");
		this.saveAction1.ShortLabel = "Save Data";
		w1.Add(this.saveAction1, null);
		this.executeAction1 = new global::Gtk.Action("executeAction1", "Edit Demographics", null, "gtk-execute");
		this.executeAction1.ShortLabel = "Edit Demographics";
		w1.Add(this.executeAction1, null);
		this.convertAction = new global::Gtk.Action("convertAction", "Edit Stimulus", null, "gtk-convert");
		this.convertAction.ShortLabel = "Edit Stimulus";
		w1.Add(this.convertAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = "MainWindow";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='FileAction1' action='FileAction1'><menu name='SessionsAction' action='SessionsAction'><menuitem name='NewRealTimeSessionAction' action='NewRealTimeSessionAction'/><menuitem name='SaveRealTimeSessionTemplateAction' action='SaveRealTimeSessionTemplateAction'/><menuitem name='LoadRealTimeSessionTemplateAction' action='LoadRealTimeSessionTemplateAction'/><separator/><menuitem name='NewPostSessionAction' action='NewPostSessionAction'/><menuitem name='SavePostSessionAction' action='SavePostSessionAction'/><menuitem name='LoadPostSessionAction' action='LoadPostSessionAction'/><separator/><menuitem name='LoadDataFileAction' action='LoadDataFileAction'/></menu><menuitem name='PreferencesAction' action='PreferencesAction'/><menuitem name='ExitAction' action='ExitAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar3'><toolitem name='zoomInAction' action='zoomInAction'/><toolitem name='zoomOutAction' action='zoomOutAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='aboutAction' action='aboutAction'/><toolitem name='findAction' action='findAction'/></toolbar></ui>");
		this.toolbar3 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar3")));
		this.toolbar3.Name = "toolbar3";
		this.toolbar3.ShowArrow = false;
		this.GtkAlignment3.Add(this.toolbar3);
		this.frame4.Add(this.GtkAlignment3);
		this.GtkLabel2 = new global::Gtk.Label();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = "<b>Display Settings</b>";
		this.GtkLabel2.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel2;
		this.hbox8.Add(this.frame4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.frame4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'SingleDisplay\' action=\'SingleDisplay" +
				"\'/><toolitem name=\'DualDisplay\' action=\'DualDisplay\'/></toolbar></ui>");
		this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
		this.toolbar4.Name = "toolbar4";
		this.toolbar4.ShowArrow = false;
		this.GtkAlignment5.Add(this.toolbar4);
		this.frame1.Add(this.GtkAlignment5);
		this.GtkLabel10 = new global::Gtk.Label();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = "<b>Data Views</b>";
		this.GtkLabel10.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel10;
		this.hbox8.Add(this.frame1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.frame1]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'><toolitem name=\'preferencesAction1\' action=\'preferen" +
				"cesAction1\'/><toolitem name=\'yesAction\' action=\'yesAction\'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.GtkAlignment4.Add(this.toolbar1);
		this.frame6.Add(this.GtkAlignment4);
		this.GtkLabel3 = new global::Gtk.Label();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = "<b>Analysis Pipeline</b>";
		this.GtkLabel3.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel3;
		this.hbox8.Add(this.frame6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.frame6]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment9 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment9.Name = "GtkAlignment9";
		this.GtkAlignment9.LeftPadding = ((uint)(12));
		// Container child GtkAlignment9.Gtk.Container+ContainerChild
		this.UIManager.AddUiFromString(@"<ui><toolbar name='toolbar5'><toolitem name='addAction1' action='addAction1'/><toolitem name='saveAction1' action='saveAction1'/><toolitem name='executeAction1' action='executeAction1'/><toolitem name='convertAction' action='convertAction'/></toolbar></ui>");
		this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar5")));
		this.toolbar5.Name = "toolbar5";
		this.toolbar5.ShowArrow = false;
		this.GtkAlignment9.Add(this.toolbar5);
		this.frame3.Add(this.GtkAlignment9);
		this.GtkLabel12 = new global::Gtk.Label();
		this.GtkLabel12.Name = "GtkLabel12";
		this.GtkLabel12.LabelProp = "<b>Data Management</b>";
		this.GtkLabel12.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel12;
		this.hbox8.Add(this.frame3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.frame3]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed15 = new global::Gtk.Fixed();
		this.fixed15.Name = "fixed15";
		this.fixed15.HasWindow = false;
		this.hbox8.Add(this.fixed15);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.fixed15]));
		w15.Position = 4;
		this.vbox1.Add(this.hbox8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox8]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 636;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.DatFrame1 = new global::Gtk.Frame();
		this.DatFrame1.Name = "DatFrame1";
		this.DatFrame1.BorderWidth = ((uint)(10));
		// Container child DatFrame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.drawingareaMain = new global::Gtk.DrawingArea();
		this.drawingareaMain.HeightRequest = 481;
		this.drawingareaMain.Name = "drawingareaMain";
		this.vbox2.Add(this.drawingareaMain);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.drawingareaMain]));
		w17.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.expander1 = new global::Gtk.Expander(null);
		this.expander1.CanFocus = true;
		this.expander1.Name = "expander1";
		this.expander1.Expanded = true;
		// Container child expander1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed();
		this.fixed5.HeightRequest = 36;
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.vbox3.Add(this.fixed5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed5]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = "Data to Display";
		this.hbox1.Add(this.label1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label1]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.AppendText("Raw Data");
		this.combobox1.Name = "combobox1";
		this.combobox1.Active = 0;
		this.hbox1.Add(this.combobox1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox1]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox1.Add(this.fixed1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
		w22.Position = 2;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = "Display Type";
		this.hbox1.Add(this.label3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label3]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.combobox3 = global::Gtk.ComboBox.NewText();
		this.combobox3.AppendText("Standard plot");
		this.combobox3.AppendText("Waterfall plot");
		this.combobox3.AppendText("Topographic map");
		this.combobox3.Name = "combobox3";
		this.combobox3.Active = 0;
		this.hbox1.Add(this.combobox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox3]));
		w24.Position = 4;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame11 = new global::Gtk.Frame();
		this.frame11.Name = "frame11";
		this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame11.Gtk.Container+ContainerChild
		this.GtkAlignment7 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment7.Name = "GtkAlignment7";
		this.GtkAlignment7.LeftPadding = ((uint)(12));
		// Container child GtkAlignment7.Gtk.Container+ContainerChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview8 = new global::Gtk.TextView();
		this.textview8.CanFocus = true;
		this.textview8.Name = "textview8";
		this.textview8.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow2.Add(this.textview8);
		this.GtkAlignment7.Add(this.GtkScrolledWindow2);
		this.frame11.Add(this.GtkAlignment7);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = "<b>Comments</b>";
		this.GtkLabel6.UseMarkup = true;
		this.frame11.LabelWidget = this.GtkLabel6;
		this.vbox3.Add(this.frame11);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.frame11]));
		w29.Position = 2;
		this.expander1.Add(this.vbox3);
		this.GtkLabel8 = new global::Gtk.Label();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = "<b>Settings</b>";
		this.GtkLabel8.UseMarkup = true;
		this.expander1.LabelWidget = this.GtkLabel8;
		this.vbox2.Add(this.expander1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.expander1]));
		w31.Position = 2;
		this.GtkAlignment.Add(this.vbox2);
		this.DatFrame1.Add(this.GtkAlignment);
		this.GtkLabelData1 = new global::Gtk.Label();
		this.GtkLabelData1.Name = "GtkLabelData1";
		this.GtkLabelData1.LabelProp = "<b>Data View 1</b>";
		this.GtkLabelData1.UseMarkup = true;
		this.DatFrame1.LabelWidget = this.GtkLabelData1;
		this.hpaned1.Add(this.DatFrame1);
		global::Gtk.Paned.PanedChild w34 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.DatFrame1]));
		w34.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.DataFrame2 = new global::Gtk.Frame();
		this.DataFrame2.Name = "DataFrame2";
		this.DataFrame2.BorderWidth = ((uint)(10));
		// Container child DataFrame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.drawingareaMain1 = new global::Gtk.DrawingArea();
		this.drawingareaMain1.HeightRequest = 481;
		this.drawingareaMain1.Name = "drawingareaMain1";
		this.vbox4.Add(this.drawingareaMain1);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.drawingareaMain1]));
		w35.Position = 0;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hseparator2]));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.expander2 = new global::Gtk.Expander(null);
		this.expander2.CanFocus = true;
		this.expander2.Name = "expander2";
		this.expander2.Expanded = true;
		// Container child expander2.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed();
		this.fixed6.HeightRequest = 36;
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.vbox5.Add(this.fixed6);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.fixed6]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = "Data to Display";
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox2 = global::Gtk.ComboBox.NewText();
		this.combobox2.AppendText("Raw Data");
		this.combobox2.Name = "combobox2";
		this.combobox2.Active = 0;
		this.hbox2.Add(this.combobox2);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.combobox2]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox2.Add(this.fixed2);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed2]));
		w40.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = "Display Type";
		this.hbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label4]));
		w41.Position = 3;
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.combobox4 = global::Gtk.ComboBox.NewText();
		this.combobox4.AppendText("Standard plot");
		this.combobox4.AppendText("Waterfall plot");
		this.combobox4.AppendText("Topographic map");
		this.combobox4.Name = "combobox4";
		this.combobox4.Active = 0;
		this.hbox2.Add(this.combobox4);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.combobox4]));
		w42.Position = 4;
		w42.Expand = false;
		w42.Fill = false;
		this.vbox5.Add(this.hbox2);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame13 = new global::Gtk.Frame();
		this.frame13.Name = "frame13";
		this.frame13.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame13.Gtk.Container+ContainerChild
		this.GtkAlignment8 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment8.Name = "GtkAlignment8";
		this.GtkAlignment8.LeftPadding = ((uint)(12));
		// Container child GtkAlignment8.Gtk.Container+ContainerChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview7 = new global::Gtk.TextView();
		this.textview7.CanFocus = true;
		this.textview7.Name = "textview7";
		this.textview7.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add(this.textview7);
		this.GtkAlignment8.Add(this.GtkScrolledWindow1);
		this.frame13.Add(this.GtkAlignment8);
		this.GtkLabel7 = new global::Gtk.Label();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = "<b>Comments</b>";
		this.GtkLabel7.UseMarkup = true;
		this.frame13.LabelWidget = this.GtkLabel7;
		this.vbox5.Add(this.frame13);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame13]));
		w47.Position = 2;
		this.expander2.Add(this.vbox5);
		this.GtkLabel9 = new global::Gtk.Label();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = "<b>Settings</b>";
		this.GtkLabel9.UseMarkup = true;
		this.expander2.LabelWidget = this.GtkLabel9;
		this.vbox4.Add(this.expander2);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.expander2]));
		w49.Position = 2;
		this.GtkAlignment1.Add(this.vbox4);
		this.DataFrame2.Add(this.GtkAlignment1);
		this.GtkLabelData2 = new global::Gtk.Label();
		this.GtkLabelData2.Name = "GtkLabelData2";
		this.GtkLabelData2.LabelProp = "<b>Data View 2</b>";
		this.GtkLabelData2.UseMarkup = true;
		this.DataFrame2.LabelWidget = this.GtkLabelData2;
		this.hpaned1.Add(this.DataFrame2);
		this.hbox3.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hpaned1]));
		w53.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox3.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator1]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.drawingareaSDG = new global::Gtk.DrawingArea();
		this.drawingareaSDG.WidthRequest = 423;
		this.drawingareaSDG.HeightRequest = 132;
		this.drawingareaSDG.Name = "drawingareaSDG";
		this.GtkAlignment2.Add(this.drawingareaSDG);
		this.frame5.Add(this.GtkAlignment2);
		this.GtkLabel11 = new global::Gtk.Label();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = "<b>Probe</b>";
		this.GtkLabel11.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel11;
		this.vbox6.Add(this.frame5);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame5]));
		w57.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed();
		this.fixed3.HeightRequest = 262;
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.vbox6.Add(this.fixed3);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.fixed3]));
		w58.Position = 1;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.frame10 = new global::Gtk.Frame();
		this.frame10.Name = "frame10";
		this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame10.Gtk.Container+ContainerChild
		this.GtkAlignment6 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment6.Name = "GtkAlignment6";
		this.GtkAlignment6.LeftPadding = ((uint)(12));
		// Container child GtkAlignment6.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar2\'><toolitem name=\'addAction\' action=\'addAction\'/><tool" +
				"item name=\'Action1\' action=\'Action1\'/><toolitem name=\'executeAction\' action=\'exe" +
				"cuteAction\'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.vbox7.Add(this.toolbar2);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.toolbar2]));
		w59.Position = 0;
		w59.Expand = false;
		w59.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewData = new global::Gtk.TreeView();
		this.treeviewData.CanFocus = true;
		this.treeviewData.Name = "treeviewData";
		this.GtkScrolledWindow.Add(this.treeviewData);
		this.vbox7.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow]));
		w61.Position = 1;
		this.GtkAlignment6.Add(this.vbox7);
		this.frame10.Add(this.GtkAlignment6);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = "<b>Loaded Data</b>";
		this.GtkLabel5.UseMarkup = true;
		this.frame10.LabelWidget = this.GtkLabel5;
		this.vbox6.Add(this.frame10);
		global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.frame10]));
		w64.Position = 2;
		this.hbox3.Add(this.vbox6);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox6]));
		w65.Position = 2;
		w65.Expand = false;
		w65.Fill = false;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w66.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
		w67.Position = 3;
		w67.Expand = false;
		w67.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1655;
		this.DefaultHeight = 900;
		this.DataFrame2.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.ToggleDisplayCountButton.Toggled += new global::System.EventHandler(this.ToggleMainDisplayCount);
		this.LoadDataFileAction.Activated += new global::System.EventHandler(this.LoadDataFile);
		this.Action.Activated += new global::System.EventHandler(this.TestRun);
		this.preferencesAction.Activated += new global::System.EventHandler(this.Pipeline_Widget);
		this.preferencesAction1.Activated += new global::System.EventHandler(this.PipelineManagerGUI);
		this.yesAction.Activated += new global::System.EventHandler(this.RunOfflineAnalysis);
		this.addAction.Activated += new global::System.EventHandler(this.LoadDataFile);
		this.ToggleRTMode.Toggled += new global::System.EventHandler(this.ChangeModeRT);
		this.SingleDisplay.Activated += new global::System.EventHandler(this.ToggleMainDisplayCount);
		this.DualDisplay.Activated += new global::System.EventHandler(this.ToggleMainDisplayCount);
		this.aboutAction.Activated += new global::System.EventHandler(this.AutoScale);
		this.drawingareaMain.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.MainWindow1ButtonPress);
		this.drawingareaMain1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.MainWindow1ButtonPress);
		this.treeviewData.RowActivated += new global::Gtk.RowActivatedHandler(this.SelectData);
	}
}
