
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action OpenFileAction;

	private global::Gtk.Action ExitAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action OpenFIleAction;

	private global::Gtk.Action ExitAction1;

	private global::Gtk.VBox vbox6;

	private global::Gtk.MenuBar menubar3;

	private global::Gtk.Notebook notebook3;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox5;

	private global::Gtk.DrawingArea drawingareaData;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.HBox hbox4;

	private global::Gtk.ComboBox comboboxdataEntry;

	private global::Gtk.ComboBox comboboxWhichData;

	private global::Gtk.Fixed fixed5;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Label GtkLabel5;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.DrawingArea drawingareaSDG;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.CheckButton checkbuttonProbe3D;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.VBox vbox4;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView textview5;

	private global::Gtk.Label label1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView textview3;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView textview1;

	private global::Gtk.Label GtkLabel9;

	private global::Gtk.Label label5;

	private global::Gtk.Statusbar statusbar1;

	private global::Gtk.Label label6;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction, null);
		this.OpenFileAction = new global::Gtk.Action("OpenFileAction", global::Mono.Unix.Catalog.GetString("Open File"), null, null);
		this.OpenFileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open File");
		w1.Add(this.OpenFileAction, null);
		this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction, null);
		this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
		w1.Add(this.FileAction1, null);
		this.OpenFIleAction = new global::Gtk.Action("OpenFIleAction", global::Mono.Unix.Catalog.GetString("Open FIle"), null, null);
		this.OpenFIleAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Open FIle");
		w1.Add(this.OpenFIleAction, null);
		this.ExitAction1 = new global::Gtk.Action("ExitAction1", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
		this.ExitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
		w1.Add(this.ExitAction1, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar3\'><menu name=\'FileAction1\' action=\'FileAction1\'><menui" +
				"tem name=\'OpenFIleAction\' action=\'OpenFIleAction\'/><menuitem name=\'ExitAction1\' " +
				"action=\'ExitAction1\'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox6.Add(this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.notebook3 = new global::Gtk.Notebook();
		this.notebook3.CanFocus = true;
		this.notebook3.Name = "notebook3";
		this.notebook3.CurrentPage = 0;
		this.notebook3.TabPos = ((global::Gtk.PositionType)(0));
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.WidthRequest = 588;
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.drawingareaData = new global::Gtk.DrawingArea();
		this.drawingareaData.Name = "drawingareaData";
		this.vbox5.Add(this.drawingareaData);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.drawingareaData]));
		w3.Position = 0;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.comboboxdataEntry = global::Gtk.ComboBox.NewText();
		this.comboboxdataEntry.AppendText(global::Mono.Unix.Catalog.GetString("/nirs/data1"));
		this.comboboxdataEntry.AppendText(global::Mono.Unix.Catalog.GetString("/nirs/data2"));
		this.comboboxdataEntry.Name = "comboboxdataEntry";
		this.comboboxdataEntry.Active = 0;
		this.hbox4.Add(this.comboboxdataEntry);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.comboboxdataEntry]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.comboboxWhichData = global::Gtk.ComboBox.NewText();
		this.comboboxWhichData.AppendText(global::Mono.Unix.Catalog.GetString("raw 690"));
		this.comboboxWhichData.Name = "comboboxWhichData";
		this.comboboxWhichData.Active = 0;
		this.hbox4.Add(this.comboboxWhichData);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.comboboxWhichData]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox4.Add(this.fixed5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.fixed5]));
		w6.Position = 2;
		this.GtkAlignment2.Add(this.hbox4);
		this.frame5.Add(this.GtkAlignment2);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Display Options</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel4;
		this.vbox5.Add(this.frame5);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame5]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.GtkAlignment1.Add(this.vbox5);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel5 = new global::Gtk.Label();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Data</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.hbox1.Add(this.frame3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.frame3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.WidthRequest = 289;
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.drawingareaSDG = new global::Gtk.DrawingArea();
		this.drawingareaSDG.Name = "drawingareaSDG";
		this.GtkAlignment.Add(this.drawingareaSDG);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Probe</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel6;
		this.vbox2.Add(this.frame1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
		w15.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.checkbuttonProbe3D = new global::Gtk.CheckButton();
		this.checkbuttonProbe3D.CanFocus = true;
		this.checkbuttonProbe3D.Name = "checkbuttonProbe3D";
		this.checkbuttonProbe3D.Label = global::Mono.Unix.Catalog.GetString("Show Registered Probe");
		this.checkbuttonProbe3D.DrawIndicator = true;
		this.checkbuttonProbe3D.UseUnderline = true;
		this.vbox2.Add(this.checkbuttonProbe3D);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkbuttonProbe3D]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.textview5 = new global::Gtk.TextView();
		this.textview5.CanFocus = true;
		this.textview5.Name = "textview5";
		this.GtkScrolledWindow2.Add(this.textview5);
		this.vbox4.Add(this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow2]));
		w19.Position = 0;
		this.notebook1.Add(this.vbox4);
		// Notebook tab
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("File Info");
		this.notebook1.SetTabLabel(this.vbox4, this.label1);
		this.label1.ShowAll();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textview3 = new global::Gtk.TextView();
		this.textview3.CanFocus = true;
		this.textview3.Name = "textview3";
		this.GtkScrolledWindow1.Add(this.textview3);
		this.notebook1.Add(this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow1]));
		w22.Position = 1;
		// Notebook tab
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Demographics");
		this.notebook1.SetTabLabel(this.GtkScrolledWindow1, this.label3);
		this.label3.ShowAll();
		this.vbox2.Add(this.notebook1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.notebook1]));
		w23.Position = 3;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.notebook3.Add(this.hbox1);
		// Notebook tab
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Data View");
		this.notebook3.SetTabLabel(this.hbox1, this.label4);
		this.label4.ShowAll();
		// Container child notebook3.Gtk.Notebook+NotebookChild
		this.frame7 = new global::Gtk.Frame();
		this.frame7.Name = "frame7";
		this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
		this.frame7.BorderWidth = ((uint)(30));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add(this.textview1);
		this.GtkAlignment3.Add(this.GtkScrolledWindow);
		this.frame7.Add(this.GtkAlignment3);
		this.GtkLabel9 = new global::Gtk.Label();
		this.GtkLabel9.Name = "GtkLabel9";
		this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString("<b>SNIRF (HDF5) File Info</b>");
		this.GtkLabel9.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel9;
		this.notebook3.Add(this.frame7);
		global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3[this.frame7]));
		w29.Position = 1;
		// Notebook tab
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("HDF5 Info");
		this.notebook3.SetTabLabel(this.frame7, this.label5);
		this.label5.ShowAll();
		this.vbox6.Add(this.notebook3);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.notebook3]));
		w30.Position = 1;
		// Container child vbox6.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		// Container child statusbar1.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label();
		this.label6.Name = "label6";
		this.statusbar1.Add(this.label6);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.statusbar1[this.label6]));
		w31.Position = 2;
		w31.Expand = false;
		w31.Fill = false;
		this.vbox6.Add(this.statusbar1);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.statusbar1]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		this.Add(this.vbox6);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 956;
		this.DefaultHeight = 498;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.OpenFileAction.Activated += new global::System.EventHandler(this.LoadFile);
		this.ExitAction.Activated += new global::System.EventHandler(this.Exit);
		this.OpenFIleAction.Activated += new global::System.EventHandler(this.LoadFile);
		this.ExitAction1.Activated += new global::System.EventHandler(this.Exit);
		this.comboboxdataEntry.Changed += new global::System.EventHandler(this.ChangeData);
		this.comboboxWhichData.Changed += new global::System.EventHandler(this.ChangeWavelength);
		this.checkbuttonProbe3D.Toggled += new global::System.EventHandler(this.ChangeProbe3D);
	}
}
